services:
  postgres:
    image: postgres:16-alpine
    container_name: kervan-postgres
    environment:
      POSTGRES_USER: kervan
      POSTGRES_PASSWORD: kervan_password
      POSTGRES_DB: kervan
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  redis:
    image: redis:7-alpine
    container_name: kervan-redis
    ports:
      - "6379:6379"


volumes:
  postgres_data:
